// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsrLUmOfBLs8bWMwijdt2SmK1DUccY-Qw',
    appId: '1:179016602172:web:ce0d355374ddbad08fe939',
    messagingSenderId: '179016602172',
    projectId: 'flutter-login-60065',
    authDomain: 'flutter-login-60065.firebaseapp.com',
    storageBucket: 'flutter-login-60065.appspot.com',
    measurementId: 'G-NSLRTNHF35',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRKmRzygsK5G9PCZaNPKuInKCePy6Q5ME',
    appId: '1:179016602172:android:0447d85a66a2bf6f8fe939',
    messagingSenderId: '179016602172',
    projectId: 'flutter-login-60065',
    storageBucket: 'flutter-login-60065.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzd2krecXwVipw4HX0KyzvcNZr6TN-UkE',
    appId: '1:179016602172:ios:749728d1f11c05db8fe939',
    messagingSenderId: '179016602172',
    projectId: 'flutter-login-60065',
    storageBucket: 'flutter-login-60065.appspot.com',
    androidClientId: '179016602172-1udvcg6t2gnqeb04t0ttft9j9lklscf0.apps.googleusercontent.com',
    iosClientId: '179016602172-jmq3bvntvpe6k2qr9uodo8t4c70cgbss.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzd2krecXwVipw4HX0KyzvcNZr6TN-UkE',
    appId: '1:179016602172:ios:16b79bf4c16cabc98fe939',
    messagingSenderId: '179016602172',
    projectId: 'flutter-login-60065',
    storageBucket: 'flutter-login-60065.appspot.com',
    androidClientId: '179016602172-1udvcg6t2gnqeb04t0ttft9j9lklscf0.apps.googleusercontent.com',
    iosClientId: '179016602172-nnhgdriqko1cmvtdo8olr17865trrebs.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleLogin.RunnerTests',
  );
}
